#!/usr/bin/env python3

"""
Generate a block to put in the CHANGELOG.md file.
"""

import os
import re
from argparse import ArgumentParser
from subprocess import check_output


EXCLUDE = ["Weblate (bot)"]

last_tag = (
    check_output(["git", "tag", "--sort=creatordate"], text=True)
    .strip()
    .split("\n")[-1]
)

args_parser = ArgumentParser()
args_parser.add_argument(
    "until",
    nargs="?",
    default="HEAD",
    help="Consider all commits until this one (default: %(default)s).",
)
args_parser.add_argument(
    "since",
    nargs="?",
    default=last_tag,
    help="Consider all commits since this one (default: %(default)s).",
)
args = args_parser.parse_args()

url = check_output(["git", "remote", "get-url", "origin"], text=True).strip()
GIT_URL_RE = re.compile(r"^git@([\w.-]+):([\w/_.-]+).git")
url = GIT_URL_RE.sub(r"https://\1/\2", url)

log_range = args.since + ".." + args.until
command = [
    "git",
    "log",
    log_range,
    "--no-merges",
    "--reverse",
    "--perl-regexp",
    "--author=^((?!(renovate|dependabot)\\[bot\\]))",
    f"--format=- %s ([%h]({url}/commit/%h))",
]
# print(command)
print(check_output(command, text=True).strip())
